<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Tagger Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\$noop\(</string>
			<key>comment</key>
			<string>Comments ($noop(...))</string>
			<key>end</key>
			<string>(?&lt;!\\)\)</string>
			<key>name</key>
			<string>comment.block.tagger_script</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parantheses</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$(?!noop)[a-zA-Z][_a-zA-Z0-9]*\(</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.tagger_script</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Functions</string>
			<key>end</key>
			<string>(?&lt;!\\)\)</string>
			<key>name</key>
			<string>meta.tagger_script</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\\),</string>
					<key>name</key>
					<string>support.function.tagger_script</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Variables</string>
			<key>match</key>
			<string>%[_a-zA-Z0-9:]*%</string>
			<key>name</key>
			<string>variable.parameter.tagger_script</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Escape sequences</string>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>keyword.other.tagger_script</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>parantheses</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)\(</string>
			<key>end</key>
			<string>(?&lt;!\\)\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parantheses</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tagger_script</string>
	<key>uuid</key>
	<string>d80e9c7b-4012-4168-97b7-64ac0ac5af0e</string>
</dict>
</plist>
